import builder from 'xmlbuilder';

import {
  nextId
} from './util/index.js';

const xmlns = 'https://www.omg.org/spec/DMN/20191111/MODEL/';

const xmlnsDmndi = 'https://www.omg.org/spec/DMN/20191111/DMNDI/';

const xmlnsDc = 'http://www.omg.org/spec/DMN/20180521/DC/';

const id = 'AutoGeneratedDmn';

const name = 'DRD';

const namespace = 'http://camunda.org/schema/1.0/dmn';


// API //////////////////////////

/**
 * @param {Array} dmnContents
 * @returns {String}
 */
export const buildXmlFromDmnContent = (dmnContents) => {
  let base = generateBaseNodes();

  let edges = [];

  dmnContents.forEach(sheet => {
    const {
      id,
      name,
      links,
      rules,
      inputs,
      outputs,
      hitPolicy,
      aggregation
    } = sheet;

    // (1) generate decision table contents
    const ruleNodes = generateRuleNodes(rules);
    const inputNodes = generateInputNodes(inputs);
    const outputNodes = generateOutputNodes(outputs);
    const decisionTable = {
      '@id': nextId('DecisionTable_'),
      input: inputNodes,
      output: outputNodes,
      rule: ruleNodes
    };

    if (hitPolicy !== 'UNIQUE') {
      decisionTable['@hitPolicy'] = hitPolicy;
      if (aggregation) {
        decisionTable['@aggregation'] = aggregation;
      }
    }

    // (2) add to definitions
    const decision = {
      '@id': id ? id : nextId('Decision_'),
      '@name': name,
      decisionTable
    };

    let decisionElement = base.ele({ decision });

    if (links) {
      for (const link of links) {
        const requiredDecision = {
          '@href': link.href,
        };
        const id = nextId('InformationRequirement_');
        const informationRequirement = {
          '@id': id,
          requiredDecision,
        };
        decisionElement.ele({ informationRequirement });

        edges.push({ href: id, points: link.edges });
      }
    }
  });

  let dmndi = base.ele('dmndi:DMNDI');
  let dmnDiagram = dmndi.ele('dmndi:DMNDiagram');
  dmnDiagram.att('id', nextId('DMNDiagram_'));

  dmnContents.forEach(sheet => {
    const {
      id,
      bounds,
    } = sheet;

    let shape = dmnDiagram.ele('dmndi:DMNShape');
    shape.att('id', nextId('DMNShape_'));
    shape.att('dmnElementRef', id);
    let shapeBounds = shape.ele('dc:Bounds');
    shapeBounds.att('x', bounds[0]);
    shapeBounds.att('y', bounds[1]);
    shapeBounds.att('width', bounds[2]);
    shapeBounds.att('height', bounds[3]);
  });

  for (const edge of edges) {
    let edgeElement = dmnDiagram.ele('dmndi:DMNEdge');
    edgeElement.att('id', nextId('DMNEdge_'));
    edgeElement.att('dmnElementRef', edge.href);
    for (const point of edge.points) {
      let pointElement = edgeElement.ele('di:waypoint');
      pointElement.att('x', point.x);
      pointElement.att('y', point.y);
    }
  }

  return base.end({ pretty: true });
};


// helper ///////////////////


const generateBaseNodes = () => {
  return builder.create({ 'definitions': { '@xmlns': xmlns,
    '@xmlns:dmndi': xmlnsDmndi,
    '@xmlns:dc': xmlnsDc,
    '@id': id,
    '@name':name,
    '@namespace': namespace } });
};

const generateRuleNodes = (rules = []) => {
  return rules.map(rule => {

    const inputEntries = rule.inputEntries.map(entry => {
      return {
        '@id': entry.id,
        'text': entry.text
      };
    });

    const outputEntries = rule.outputEntries.map(entry => {
      return {
        '@id': entry.id,
        'text': entry.text
      };
    });

    return {
      '@id': rule.id,
      description: rule.description,
      inputEntry: inputEntries,
      outputEntry: outputEntries
    };
  });
};

const generateInputNodes = (inputs = []) => {
  return inputs.map(input => {
    return {
      '@id': input.id,
      '@label': input.label.trim(),
      inputExpression: {
        '@id': input.inputExpression.id,
        '@typeRef': input.inputExpression.typeRef,
        text: input.inputExpression.text.trim()
      }
    };
  });
};

const generateOutputNodes = (outputs = []) => {
  return outputs.map(output => {
    return {
      '@id': output.id,
      '@label': output.text.trim(),
      '@name': output.name.trim(),
      '@typeRef': output.typeRef
    };
  });
};
